### ISSUE TITLE
onDataMsgArrived被调用后，如何发起下一次请求？

### ISSUE THREAD

**Issue by pcenshao** [kyleduo/iCometClient4j#3]
onDataMsgArrived被调用后，如何发起下一次请求？

你好，感谢你开源的代码。

我现在遇到的问题是，在收到第一个消息后就无法再收到消息了。

SubThread代码中，在收到Type.TYPE_DATA消息后，没有发起下一次请求，这导致“中连接”没有保持，**无法再收到下一个消息了**。

在SubThread中：
`if (msg.type.equals(Message.Type.TYPE_DATA) && msg.content != null && msg.content.length() > 0) {
                            // here comes a data message
                            Message.Content content = gson.fromJson(msg.content, Message.Content.class);
                            mChannel.seq++;
                            mICometCallback.onDataMsgArrived(content);

```
                    }`
```

mChannel.seq是进行了递增操作，但却未找到使用它的地方。

请不吝赐教，谢谢。

**Comment by sunyuancun** [comment]
你好   这个 没必要mChannel.seq++;       seq 是固定的吧

**Comment by sunyuancun** [comment]
你好 有没有遇到   后台长时间休眠   收不到消息的情况 （心跳消息不存在了）  如何解决的
