### ISSUE TITLE
使用IComet发现的一个问题

### ISSUE THREAD

**Issue by jessos** [kyleduo/iCometClient4j#4]
您好，我的APP中使用的就是您的iCometClient4j。但是现在出现了一个问题，就是手机连着wifi，但是路由器已经被拔掉网线，这时候IComet好像处于了假死状态。希望能得到您的帮助，不胜感激。

**Comment by sunyuancun** [comment]
您好   您是如何  处理 心跳断开的情况的     

我的是 在休眠一段时间后   收不到消息

**Comment by jessos** [comment]
@sunyuancun  设置readTimeout
